```{r}
library(ggplot2)
#install.packages("mice") # if you don't have it already
library(mice)
library(plyr) # nice for re-formatting data
#install.packages("GGally") # if you don't have it already
library(GGally) # for plot matrices
set.seed(12345)
```

```{r}
lapop.2014.HND <- read.csv('2014-HND.csv')
my_data <- lapop.2014.HND[,c('honqt1','honqt2','honqt3','honqt4','honqt5','honqt6','honqt7','honqt8','honqt9','honqt10','honqt11','honqt12')]
```

```{r}
is.na(my_data[my_data>16]) <- TRUE
nrow(na.omit(my_data))
```

```{r}
sum(is.na(my_data)) / (nrow(my_data)*ncol(my_data))
```

```{r}
my_complete <- na.omit(my_data)
pr_complete <- prcomp(my_complete,center=TRUE,scale=FALSE)
plot(pr_complete)
summary(pr_complete)
```

```{r}
my_imp <- mice(my_data,printFlag = F) 
my_imp
```

```{r}
pr <- lapply(1:5,function(x) prcomp(complete(my_imp,x),scale=FALSE,center=TRUE))
plot(pr[[1]])
summary(pr[[1]])
```

```{r}
pc1 <- pr[[1]]$x[,1]
pc2 <- pr[[1]]$x[,2]
qplot(pc1,pc2)
```

```{r}
all_pc1 <- data.frame(llply(1:5, function(i) pr[[i]]$x[,1]))
names(all_pc1) <- c('imp1','imp2','imp3','imp4','imp5')
ggpairs(all_pc1) + theme_classic()
```

```{r}
all_pc1$avg <- rowMeans(all_pc1)
quantile(all_pc1$avg)
colMeans(my_data[all_pc1$avg < quantile(all_pc1$avg)[2],],na.rm=TRUE)
colMeans(my_data[all_pc1$avg > quantile(all_pc1$avg)[4],],na.rm=TRUE)
```

```{r}
all_pc1$norm <- scale(all_pc1$avg)
```

```{r}
predict_data <- data.frame(honqt1=c(1,4),honqt2=c(1,4),honqt3=c(1,4),honqt4=c(1,4),honqt5=c(1,4),honqt6=c(1,4),honqt7=c(1,4),honqt8=c(1,4),honqt9=c(1,4),honqt10=c(1,4),honqt11=c(1,4),honqt12=c(1,4))
minmax <- rowMeans(sapply(1:5, function(i) predict(pr[[i]],predict_data)[,1]))
minmax <- (minmax-mean(all_pc1$avg)) / sd(all_pc1$avg)

predict_data2 <- data.frame(diag(12)+1)
names(predict_data2) <- names(my_data)
scores <- rowMeans(sapply(1:5, function(i) predict(pr[[i]],predict_data2)[,1]))
scores <- (scores-mean(all_pc1$avg)) / sd(all_pc1$avg)
diff <- data.frame(d=(scores - minmax[1]),n=names(predict_data))
ggplot(diff,aes(x=n,y=d)) +
  geom_bar(stat='identity',fill='skyblue') +
  coord_flip() +
  theme_classic() +
  theme(text=element_text(size=20),
        axis.title.y=element_blank(),
        axis.title.x=element_blank())
```

```{r}
lmp <- function (modelobject) {
    if (class(modelobject) != "lm") stop("Not an object of class 'lm' ")
    f <- summary(modelobject)$fstatistic
    p <- pf(f[1],f[2],f[3],lower.tail=F)
    attributes(p) <- NULL
    return(p)
}
sapply(c('honqt1','honqt2','honqt3','honqt4','honqt5','honqt6','honqt7','honqt8','honqt9','honqt10','honqt11','honqt12'),
       function(x) lmp(lm(all_pc1$norm ~ my_data[,x])))
```

```{r}
honqt4 <- data.frame(q=my_data$honqt4,w=all_pc1$norm)
honqt4 <- na.omit(honqt4)
my_lm <- lm(data=honqt4, q ~ w)
summary(my_lm)
ggplot(honqt4,aes(x=w,y=q)) +
  geom_jitter(color='tomato3',size=5,alpha=0.2) +
  theme_classic() +
  geom_smooth(method='lm',size=2,color='royalblue') +
  annotate('text',label=paste("R-sq:",round(summary(my_lm)$r.squared,2)),  
           size=10,x=-0.5,y=2.5,hjust=0,vjust=0,color='royalblue') +
  ylab('honqt4') +
  xlab('Composite index') +
  theme(text=element_text(size=20)) 
```

